avatar = open("panda", "w", encoding="utf-8") 
avatar.write("******************\n")
avatar.write("*                *\n")
avatar.write("** * *** ** *** **\n")
avatar.write("*                *\n")
avatar.write("** ***           *\n")
avatar.write("**** ****** * ****\n")
avatar.write("*                *\n")
avatar.write("******************\n")
avatar = open("panda", "r", encoding="utf-8") 
print(avatar.read())
